### ISSUE TITLE
Need to use --no-write-json to avoid empty STG_DBT__NODE_EXECUTIONS model

### ISSUE THREAD

**Issue by sfc-gh-dflippo** [brooklyn-data/dbt_artifacts#100]
Hello, recently I was tracking down why many of my models were empty and I tracked it down to the command I was using to invoke the new upload macro:
`dbt run-operation upload_dbt_artifacts_v2`

I found that my manifest.json was being replaced by the macro's execution and that was causing the `STG_DBT__NODE_EXECUTIONS` model to have zero rows because it has an inner join between `stg_dbt__artifacts` and `stg_dbt__nodes`. In my case the issue was resolved by using this command to upload instead:
`dbt --no-write-json run-operation upload_dbt_artifacts_v2`

I recommend the README.md be updated to include the `--no-write-json` parameter. 

I also recommend committing the fix for issue #64 because that was also one of my root causes.

**Comment by NiallRees** [comment]
Thanks for finding this @danflippo !
