### ISSUE TITLE
Incremental models not populating

### ISSUE THREAD

**Issue by ghost** [brooklyn-data/dbt_artifacts#102]
Executing the below steps with latest dbt version and latest pre-release of dbt_artifacts, but data fails to load into nearly all of the tables when running incrementally.

1. dbt run-operation create_artifact_resources (builds out the starting objects as expected)
2. dbt run (runs the entire project and builds my project objects as well as dbt_artifact objects)
3. dbt run-operation upload_dbt_artifacts_v2 (uploads some data to the artifact tables correctly)
4. dbt run (_should_ incrementally add some data to the dims and facts, but nothing is added)

Have tried tracing all of it backward through stage models and incremental loads, but can't seem to narrow down an area where it's breaking down.

**Comment by alanmcruickshank** [comment]
Can you see new data being added to the artifact tables being created in step 1 above? That would help narrow down where the issue is coming from.

**Comment by ghost** [comment]
@alanmcruickshank I do see the objects created in step 1. Step 3 does upload the artifacts as expected. Step 4 does not load any data to the new tables. Currently running with --full-refresh and it does populate _some_ data, so I think this is at least partially due to PR #67. Still seeing 0 rows populated into the below tables that I would expect based on what's populated in the project, however.

DIM_DBT__CURRENT_MODELS
FCT_DBT__CRITICAL_PATH
FCT_DBT__MODEL_EXECUTIONS
INT_DBT__MODEL_EXECUTIONS

**Comment by NiallRees** [comment]
This should be resolved by https://github.com/brooklyn-data/dbt_artifacts/pull/107 which will be included in the next release
