### ISSUE TITLE
I am getting Error in Database Error in model fct_dbt__critical_path

### ISSUE THREAD

**Issue by gargvipul1349** [brooklyn-data/dbt_artifacts#109]
I am getting compilation Error in the model. Below is message it generates while running all models under dbt_atifacts module it failed with model fct_dbt__critical_path.

**2022-03-24T09:44:58.342+05:30Copy  Processing aborted due to error 300010:391167117; incident 7185034. | Processing aborted due to error 300010:391167117; incident 7185034.**

**Comment by NiallRees** [comment]
Hi @gargvipul1349, this seems like it's an unexpected error in Snowflake as opposed to an error within the package. Please could you submit a support case with Snowflake? I'm going to close this issue for now.

https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge

**Comment by gargvipul1349** [comment]
ok Sure Thanks @NiallRees
