### ISSUE TITLE
0.7.0 README references (forthcoming!) 0.8.0 functionality.

### ISSUE THREAD

**Issue by devin-hc** [brooklyn-data/dbt_artifacts#110]
Hi! I hope this format is ok for a new issue, I didn't see any explicit guidelines in the README.

Currently, the README for 0.7.0 references `..._v2` functionality concerning artifact loads, but does not contain the code (which is in the 0.8.0 prerelease branches.)

This is somewhat confusing for people currently integrating the package into their projects and should probably not already be present in the current 0.7.0 release documentation.

Thank you for all the hard work on this, very neatly solves observability issues with dbt/dbt-Cloud!!!

**Comment by NiallRees** [comment]
Hey @devin-hc - thanks for raising this. We should have created a 0.8.0 branch to keep these docs off of the front page, sorry for the confusion. 0.8.0 is now released though, so I think we're back in sync.
