### ISSUE TITLE
 0.7.0 version - Unique test failures on dim and fct models

### ISSUE THREAD

**Issue by praveenakarumuri** [brooklyn-data/dbt_artifacts#113]
we are seeing below test failures on dbt_artifacts models.

Failure in test unique_dim_dbt__current_models_manifest_model_id (models/schemas.yml)
Failure in test unique_dim_dbt__models_manifest_model_id (models/schemas.yml)
Failure in test unique_dim_dbt__sources_manifest_source_id (models/schemas.yml)
Failure in test unique_fct_dbt__critical_path_node_id (models/schemas.yml)
Failure in test unique_fct_dbt__latest_full_model_executions_node_id (models/schemas.yml)
Failure in test unique_fct_dbt__model_executions_model_execution_id (models/schemas.yml)

on investigation, we found that the below inner join fix for issue 75 is doing a 1 to many join and causing entire row duplicates. 
"-- https://github.com/brooklyn-data/dbt_artifacts/issues/75 inner join run_results on dbt_sources.artifact_run_id = run_results.artifact_run_id ) "

This is because we upload the run results after every dbt run where we generate multiple run results and single manifest. If we can change the join to where exists this duplication will be resolved as the idea is to only enforce and not pull any other fields from inne r join view.

We fixed it for time being by using 0.6.0 version.

Note: We are running this on a single tenancy dbt cloud

**Comment by devin-hc** [comment]
For what it's worth, we're having the same issue. Thanks for the current workaround.

**Comment by NiallRees** [comment]
Hi @praveenakarumuri - I've just released a new version 0.8.0. Please could you confirm if you are still seeing this issue?

**Comment by praveenakarumuri** [comment]
Hi @NiallRees - Thank you, It looks to be working fine in 0.8.0.
