### ISSUE TITLE
Documentation and Source Versioning out of Sync

### ISSUE THREAD

**Issue by GJMcClintock** [brooklyn-data/dbt_artifacts#115]
The latest README says to update to 0.8 which is still in pre-realease.

All references throughout commits and documentation reference macros `upload_dbt_artifacts` and `upload_dbt_artifacts_v2` but the macros do not have `_dbt` in the name (eg: it's `upload_artifacts_v2`.

as such, users are unable to use the documentation without digging through source code to find the issues - the front page docs for 0.7 reflect macros that are still in pre-release as well as have name differences.

**Comment by NiallRees** [comment]
Hi @GJMcClintock - I've just cut the 0.8.0 release! On the macro names - I'm not able to locate that inconsistency other than in the macro filenames, which shouldn't have any impact:

https://github.com/brooklyn-data/dbt_artifacts/blob/main/macros/upload_artifacts.sql#L1
https://github.com/brooklyn-data/dbt_artifacts/blob/main/macros/upload_artifacts_v2.sql#L1

Let me know if there's something I'm missing!

**Comment by mateusz-kmon** [comment]
I get the following error: **dbt: error: unrecognized arguments: --no-write-json**
when running dbt run-operation with the --no-write-json flag at the end as given in the documentation:
dbt run-operation upload_dbt_artifacts_v2 --no-write-json


Putting the flag directly after dbt works fine:
dbt --no-write-json run-operation upload_dbt_artifacts_v2

**Comment by NiallRees** [comment]
Thanks @mateusz-kmon - just fixed that. dbt Cloud doesn't seem to allow that flag, I'll follow up!
![image](https://user-images.githubusercontent.com/23722609/164065616-495f2944-0cc9-4faf-a068-3508e138041c.png)

**Comment by NiallRees** [comment]
Going to close this issue as I think the inconsistency is now resolved with the release of 0.8.0.
