### ISSUE TITLE
Support tap-dbt-artifacts

### ISSUE THREAD

**Issue by andrewcstewart** [brooklyn-data/dbt_artifacts#116]
I think a really interesting use case for Meltano users would be to pair `dbt_artifacts` with https://github.com/prratek/tap-dbt-artifacts

Just from eyeballing the staging models in `dbt_artifacts` and comparing them with the the [schemas](https://github.com/prratek/tap-dbt-artifacts/tree/main/tap_dbt_artifacts/schemas) generated by `tap-dbt-artifacts`, it looks like it should be pretty easy to get these two talking to each other; I can imagine a few potential approaches but would might be to create staging tables that shape the `tap-dbt-artifacts` generated tables into the form expected by the sources defined at https://github.com/brooklyn-data/dbt_artifacts/blob/main/models/staging/sources.yml 

I'm interested in taking a stab at this but would be curious for feedback on best approach from the perspective of this package's maintainers.

**Comment by NiallRees** [comment]
Hey @andrewcstewart this is a great idea. I can see this package being configurable with a variable like 'artifact_source' which could take on values along the lines of:
- 'single_artifact_table' (We call this the V1 upload method)
- 'flattened_artifact_tables' (We call this the V2 upload method)
- 'tap-dbt-artifacts' (This new thing)

The staging models would then be compiled differently depending on this variable to match the source data. What do you think?

**Comment by andrewcstewart** [comment]
Hi @NiallRees - Yeah that sounds like a good way to handle multiple sources.

I just noticed that this plugin is primarily angled towards Snowflake - I'm wondering (w/o having yet scoured the SQL dialect of the package models) if that is primarily due to the current upload method being Snowflake specific?  For example, would `tap-dbt-artifacts` open up the possibility of using different adapters?

**Comment by NiallRees** [comment]
The reason it's currently only Snowflake compatible is that the org it was originally built for were using Snowflake, the artifact upload method using `PUT` came later. Additional loading techniques absolutely opens up the possibility of adding compatibility with other warehouses though!

**Comment by NiallRees** [comment]
We've been busy reimplementing the package, opening up this package to be compatible with more adapters (adding databricks compatibility out of the gate). We'd love any feedback you have: https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1
