### ISSUE TITLE
Different ids on upload? V2

### ISSUE THREAD

**Issue by steveh-101** [brooklyn-data/dbt_artifacts#122]
I ran dbt build followed by dbt run-operation upload_dbt_artifacts_v2  - four times on empty tables

the results from this query:
```
select distinct
      artifact_run_id, command_invocation_id, 'dbt_run_results_nodes' as _source 
from dbt_artifacts.dbt_run_results_nodes

union all select distinct
    artifact_run_id, command_invocation_id, 'dbt_run_results' as _source
from dbt_artifacts.dbt_run_results

union all select distinct
    artifact_run_id, command_invocation_id, 'dbt_manifest_nodes' as _source
from dbt_artifacts.dbt_manifest_nodes

order by  _source, command_invocation_id
```

show that the ids from the manifest do not match those with the run_result nodes.

The result is empty tables after running the models from dbt_artifacts

**Comment by steveh-101** [comment]
Screenshot of my query:
![image](https://user-images.githubusercontent.com/601426/170832937-7e7ccf45-30a5-45c3-9748-9b02ffa21ff2.png)

I noticed after that the `artifact_generated_at` is also different compared to what one would expect given that it looks like manifest.json gets uploaded first?

**Comment by steveh-101** [comment]
Not sure what's causing. I checked the files themselves and they were generating different ids.

I thought it might be an 'on run start' macro that's in our project - so I disabled that. 

Tested and still produced different ids, even when checking the files manually.

Did dbt clean / deps.. and that sorted it locally.

Will keep an eye because in CI it might still be happening (we cache dbt deps on a hash of packages.yml)

**Comment by NiallRees** [comment]
Hi @rudeb0y - thank you for raising this and sorry for not responding sooner. We've been busy reimplementing the package, resolving this issue, and would love if you have any feedback! https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1
