### ISSUE TITLE
Version discrepancy between dbt Package hub and Latest version

### ISSUE THREAD

**Issue by sampaq** [brooklyn-data/dbt_artifacts#123]
When you run dbt deps to get packages from the dbt Package hub, the wrong version of dbt_artifacts is seemingly pulled.
You can easily verify this by going to https://hub.getdbt.com/brooklyn-data/dbt_artifacts/latest/ and click View on Github under the README file. Navigate to the dbt_project.yml file and see that the version is 0.6.0 instead of the latest, 0.8.0.

**Comment by NiallRees** [comment]
Hi @sampaq, I believe the issue here is that I forgot to update the version specified in the `dbt_project.yml` for that release. Rest assured that you do have the correct version of the code however. I'm going to close this out, apologies for the confusion!
