### ISSUE TITLE
dbt_artifact 0.7 FCT_DBT__SNAPSHOT_EXECUTION empty

### ISSUE THREAD

**Issue by iistudio** [brooklyn-data/dbt_artifacts#129]
hi team:

I am scratching my head on this one, I am running DBT from DBT cloud

first step is: dbt snapshot ( I have also tried dbt snapshot -s dbt_artifacts)

2nd step I run dbt run --exclude dbt_artifacts

3nd step is : dbt run-operation upload_dbt_artifacts --args '{filenames: [manifest, run_results]}'

4th step is :  dbt run -m dbt_artifacts

but after all processed, I have data in FCT_DBT__RUN_RESULTS and FCT_DBT__MODEL_EXECUTIONS
plus the DIM_DBT__SNAPSHOTS dimension is populated, I think from manifest.. 

I just dont know why the FCT_DBT__SNAPSHOT_EXECUTION doesnt? 

thanks

**Comment by iistudio** [comment]
I found out that:

I need to run dbt run_operation upload_dbt_artifacts after the dbt snapshot step..

but the fact table still not populated. error being in this sql statement from debug logs:

snapshot_executions_incremental as (

    select snapshot_executions.*
    from snapshot_executions
    -- Inner join with run results to enforce consistency and avoid race conditions.
    -- https://github.com/brooklyn-data/dbt_artifacts/issues/75
    inner join run_results on
        snapshot_executions.artifact_run_id = run_results.artifact_run_id

    
        -- this filter will only be applied on an incremental run
       where snapshot_executions.artifact_generated_at > (select max(artifact_generated_at) from dbt_artifacts.dbt_operational_insights.fct_dbt__snapshot_executions)
)

this select max(artifact_generated_at) from dbt_artifacts.dbt_operational_insights.fct_dbt__snapshot_executions) returns **NULL**

the artifact_generated_at > null returns no results in snowflake.

is there any way to get around this? I can think that I insert a dummy row into the table with the artifact_generated_at being low watermark date.

**Comment by NiallRees** [comment]
Hi @iistudio - thank you for raising this and sorry for not responding sooner. We've been busy reimplementing the package, resolving this issue, and would love if you have any feedback! https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1
