### ISSUE TITLE
Swap to result/graph objects as data source

### ISSUE THREAD

**Issue by bennieregenold7** [brooklyn-data/dbt_artifacts#130]
Hi there!

I've been playing around with this package for a while, and really like all the info it provides! I see that there are currently a few issues out there to support other warehouses, and it looks like the main thing slowing that support down is the upload of the artifacts. 

I'm curious if you have considered swapping to the context variables that dbt provides as the source of data. I haven't done an exhaustive review of the data between the two, but it looks like the [results variable](https://docs.getdbt.com/reference/dbt-jinja-functions/on-run-end-context#results) may have everything you need from run results, and the [graph variable](https://docs.getdbt.com/reference/dbt-jinja-functions/graph) may have the things you need from the manifest. Since you can pull these directly from dbt without the need to import files, it may solve some problems on that side of things.

I'm in the very early stages of thinking about a stand-alone package to parse those two variables and load them to a database into audit style tables, and thought it may be helpful here as well. 

Edit: A good example of this for the graph object is the recently released project evaluator package. [These macros](https://github.com/dbt-labs/dbt-project-evaluator/tree/main/macros/unpack) from that package show how you can parse the graph object to get info on the project.

**Comment by NiallRees** [comment]
Hi @bennieregenold7 - I'm happy to report that we are currently in the process of doing just this for the v1 release of the package! Stay tuned :)

**Comment by NiallRees** [comment]
See https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1 :)
