### ISSUE TITLE
Add selector to fct_dbt__invocations

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#135]
Requires https://github.com/dbt-labs/dbt-core/issues/5524

**Comment by smitsrr** [comment]
Plus one on wanting this feature!!

**Comment by jelstongreen** [comment]
+1 !

**Comment by jelstongreen** [comment]
@NiallRees Now that https://github.com/dbt-labs/dbt-core/issues/5524 is merged will this be up soon do you reckon?

**Comment by NiallRees** [comment]
Hey all, we're awaiting the release of @jared-rimmer's [PR here](https://github.com/dbt-labs/dbt-core/pull/5782) to be released in a version of dbt-core. That will likely be a few more weeks!
