### ISSUE TITLE
Investigate feasibility of migrating from pre v1 to v1

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#136]

**Comment by tacastillo** [comment]
👍🏽

**Comment by tacastillo** [comment]
I have the pattern+implementation down as of yesterday, just need to tinker and clean it up. Aiming to raise a PR by EOD today, but if it doesn't make the release cut, then... yeah.

**Comment by NiallRees** [comment]
Resolved by #157
