### ISSUE TITLE
Add dim_dbt__current_x model for every resource type

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#137]
-- Update - previously this issue was just about the `dim_dbt__current_models` model, but it now relates to a `dim_dbt__current_x` for every model.

Original description:

If you would like to see the return of this model in v1.0.0, please drop any feedback or thumbs up on this issue!

https://github.com/brooklyn-data/dbt_artifacts/blob/0.8.0/models/dim_dbt__current_models.sql

**Comment by alanmcruickshank** [comment]
We do use this model (I wrote it 🤷 ). In a project which refreshes different models on different schedules, this provides a single view onto the current state of the project. Last refreshes, dependency mapping and project size monitoring.

Worst case we could pull this into our own project if necessary.

**Comment by NiallRees** [comment]
Yep I like this. My thinking is:
* Create a dim_current_x version of every resource model, which is just a view representing the current state of the project
* Enrich that with the latest seen execution and results of that resource. For models this would be last run time, was it a full refresh, how long did it take etc

**Comment by NiallRees** [comment]
To update, this issue will now be closed by a PR which:
* Adds a `dim_dbt__current_x` model for every resource type, which has the current entities in the project and latest execution information for them
* The `dbt_dbt__current_models` model should have as many of the fields available in the pre-v1 version
* The `dbt_dbt__current_exposures` model should be a replacement for https://github.com/brooklyn-data/dbt_artifacts/issues/139
