### ISSUE TITLE
Add fct_dbt__critical_path back?

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#138]
If you would like to see the return of this model in v1.0.0, please drop any feedback or thumbs up on this issue!

[fct_dbt__critical_path.sql](https://github.com/brooklyn-data/dbt_artifacts/blob/0.8.0/models/fct_dbt__critical_path.sql)

**Comment by alanmcruickshank** [comment]
This model doesn't really work currently in our existing setup. See #83. Happy for it to be retired for now.
