### ISSUE TITLE
Add fct_dbt__exposures_updates back?

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#139]
If you would like to see the return of this model in v1.0.0, please drop any feedback or thumbs up on this issue!

https://github.com/brooklyn-data/dbt_artifacts/blob/0.8.0/models/fct_dbt__exposures_updates.sql

**Comment by alanmcruickshank** [comment]
We don't use this model in our setup. Happy to retire it 👍
