### ISSUE TITLE
Add fct_dbt__latest_full_model_executions back?

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#140]
If you would like to see the return of this model in v1.0.0, please drop any feedback or thumbs up on this issue!

https://github.com/brooklyn-data/dbt_artifacts/blob/0.8.0/models/fct_dbt__latest_full_model_executions.sql

**Comment by alanmcruickshank** [comment]
This model doesn't work in our current setup (because we run different marts on different schedules) - we use the `dim__current_models` one instead. Happy to retire it.

**Comment by NiallRees** [comment]
Agreed it doesn't really make sense
