### ISSUE TITLE
Not able to implement beta prerelease in dbt project

### ISSUE THREAD

**Issue by foxmulder42** [brooklyn-data/dbt_artifacts#143]
Hi

for some reason I can't implement the beta prerelease of your latest tag (1.0.0b1) in my dbt project. 

`
  - package: brooklyn-data/dbt_artifacts
    version: 1.0.0b1
    install-prerelease: true
`

`
Could not find a matching version for package brooklyn-data/dbt_artifacts
  Requested range: =1.0.0-b1, =1.0.0-b1
  Available versions: ['0.1.0', '0.2.0', '0.2.1', '0.3.0', '0.4.0', '0.4.1', '0.4.2', '0.4.3', '0.4.4', '0.5.0', '0.6.0', '0.7.0', '0.8.0']
`

Am I missing something, or is it just because you didn't hit the release button yet?

Thanks and kind regards,
Daniel

**Comment by NiallRees** [comment]
Hi @foxmulder42 - there's actually a bug in the dbt hub which is preventing pre-release versions from being installed: https://github.com/dbt-labs/hubcap/issues/129

For now, please try:
```
packages:
  - git: https://github.com/brooklyn-data/dbt_artifacts.git
    revision: 1.0.0b1
```

**Comment by foxmulder42** [comment]
Thanks @NiallRees 

worked like a charm <3
