### ISSUE TITLE
Failure in test unique_fct_dbt__run_results_command_invocation_id

### ISSUE THREAD

**Issue by emilyjia** [brooklyn-data/dbt_artifacts#158]
We're experiencing this error

```
21:25:03  Completed with 1 error and 0 warnings:
21:25:03  
21:25:03  Failure in test unique_fct_dbt__run_results_command_invocation_id (models/schemas.yml)
21:25:03    Got 1 result, configured to fail if != 0
21:25:03  
21:25:03    compiled SQL at target/compiled/dbt_artifacts/models/schemas.yml/unique_fct_dbt__run_results_command_invocation_id.sql
```

I'm trying to debug this and see that `stg_dbt__run_results.sql` has two rows for the same `command_invocation_id`, one from `stg_dbt__artifacts` and another from `dbt_run_results`. Furthermore, there is slightly different precision for `generated_at` timestamps in `stg_dbt__artifacts` vs `dbt_run_results`. 

- In `stg_dbt__artifacts` the `generated_at` timestamp is `2022-08-03 15:31:14.446465000`
- In `dbt_artifacts.dbt_run_results` the `generated_at` timestamp is `2022-08-03 15:31:14.446000000 +00:00`

As a result, in `fct_dbt__run_results` there are two rows with the same `command_invocation_id` but slightly different `artifact_generated_at`, and then the test fails. 

Is `stg_dbt__run_results` supposed to have two rows for the same `run_results` artifact? And is `fct_dbt__run_results` supposed to de-duplicate these rows to pass the test?

**Comment by NiallRees** [comment]
Hi @emilyjia - I think is an issue for an older version of the package, we're currently re-writing it in its entirety and will be releasing v1 very soon. I think the new version will solve this issue.
