### ISSUE TITLE
Add meta and tags to models 

### ISSUE THREAD

**Issue by ahmedrad** [brooklyn-data/dbt_artifacts#174]
Hey team,

I'm trying to build a visualization for dbt models and tests performance for our dbt project and need to breakdown the visualisation by tags and some metadata that we set on the models. I was pretty excited to see the release of V1 but now that the models table is populated separately and the extraction of model data is happening on the run end hook side of things there's no raw data for me to extract the information I need.

I can whip up a PR pretty quick to add tags and meta columns to the models table (tags seem to already exists on the tests table). If that's a good direction happy to take it on

Cheers,
Ahmed

**Comment by NiallRees** [comment]
Hi @ahmedrad - PR would be greatly appreciated!

**Comment by ahmedrad** [comment]
there you go: https://github.com/brooklyn-data/dbt_artifacts/pull/175

**Comment by ahmedrad** [comment]
@NiallRees would love a review on the PR when you get a chance

**Comment by ahmedrad** [comment]
Resolved: https://github.com/brooklyn-data/dbt_artifacts/pull/212
