### ISSUE TITLE
`dbt_artifacts_schema` doesn't support Jinja expression

### ISSUE THREAD

**Issue by b-per** [brooklyn-data/dbt_artifacts#181]
### The issue

I have tried defining the following:

```
vars:
  dbt_artifacts_schema: "{{target.schema}}_meta"
```

But I then get an issue when generating the tables. 

The schema is created correctly with 
```
{%- do adapter.create_schema(api.Relation.create(database=database_name, schema=var('dbt_artifacts_schema', target.schema))) -%}
```

But the following code raises an error
```
{% set src_dbt_exposures = source('dbt_artifacts', 'exposures') %}
{{ dbt_artifacts.create_exposures_table_if_not_exists(src_dbt_exposures.database, src_dbt_exposures.schema, src_dbt_exposures.identifier) }}
```

This is due to the sources having `schema: "{{ var('dbt_artifacts_schema', target.schema) }}"` defined, which is rendered to `schema: "{{target.schema}}_meta"` instead of `schema: "my_schema_meta"`.

It feels like it is a limitation due to the way Jinja and variables work in YML files.

### Alternative solution
Could a parameter be created, called `dbt_artifacts_schema_prefix`, which when defined (and when `dbt_artifacts_schema` is not defined) is added at the end of the `target.schema`? 

e.g.
```
vars:
  dbt_artifacts_schema_prefix: _meta
```
would create tables in `my_schema_meta`

**Comment by jaypeedevlin** [comment]
Hey @b-per!

You're right, this is a dbt-driven issue, although I agree the solve doesn't have to be on the dbt side!  I think this has some overlap with https://github.com/brooklyn-data/dbt_artifacts/issues/153, what do you think about closing this in favor of discussion there?

**Comment by b-per** [comment]
Yes, it makes sense!
