### ISSUE TITLE
Issue with Docs Blocks in Exposures

### ISSUE THREAD

**Issue by ZahidGalea** [brooklyn-data/dbt_artifacts#187]
Hi team.

Just started using the new support for Bigquery (v1.2.0), and I'm having an issue in the exposure description when using Docs Blocks, by some reason Bigquery is trowing the following error:

`dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unclosed string literal at [18:21]`

If I comment the description, the rest works fine. we just tested Docs blocks in exposures as it is what we use for now.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/39713883/187549496-b73b8403-f467-488e-9f5d-791bb5b9e0ad.png">

**Comment by charles-astrafy** [comment]
@ZahidGalea : I have just made a pull request to fix this
