### ISSUE TITLE
Add support for latest dbt_utils

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#190]
We currently only support dbt_utils < 0.9.0

https://github.com/dbt-labs/dbt-utils/releases

**Comment by Triangulum9r** [comment]
this is preventing me from installing use `dbt deps` as it fails with a version error

**Comment by jaypeedevlin** [comment]
@NiallRees to address this properly probably involves moving the instances of `dbt_utils.split_part()` to the cross db macros in dbt >=1.2, what do you think about me making this change as part of #188?

Bumping the deps version by itself gives us a bunch of deprecation warnings on that macro that I guess we want to avoid?

**Comment by jaypeedevlin** [comment]
Alternate idea — now that split_part lives outside of utils, maybe we copy the SK implementation into our project and remove the dependency altogether?

**Comment by NiallRees** [comment]
No strong opinions @jaypeedevlin happy for you to decide - might as well include in your PR though for sure

**Comment by jaypeedevlin** [comment]
For posterity I decided to remove the dependency altogether.

**Comment by jaypeedevlin** [comment]
This is resolved in 188 which should be released in the next week or so.
