### ISSUE TITLE
Add compile_completed_at and query_started_at to execution data

### ISSUE THREAD

**Issue by kaufmannie** [brooklyn-data/dbt_artifacts#193]
In assessing the performance of the executions (models, tests, seeds, snapshots) in dbt jobs via dbt artifact data, it is important for us to distinguish between queuing and execution time. When a model takes a long time to build because of queuing, the actions to optimize are very different than when the model takes a long time to build because of long execution. 

With the current state of the dbt artifact package, we only seem to upload and surface `started_at` from the compile stage (compile_started_at) and `ended_at` from the execution stage (query_ended_at). With this information, I can see the time of the full model build, but cannot distinguish what of that was from compilations/queuing/execution. With the full raw artifact json no longer being uploaded (flattened and only certain fields uploaded now), I cannot get this view at all. It would be great to end `ended_at` from the compile stage and `started_at` from the execution stage as well. 

Wanted to share this as something that would help with our use case of the dbt_artifacts package! We are specifically looking to have this information in the `_executions` tables that the `upload_result` macro updates when called via the `on-run-end` post hook. We are working with those tables directly. But I'm sure flowing these fields through to the models in this package would be helpful as well.

**Comment by jaypeedevlin** [comment]
Hi Kaufmannie — we could definitely consider adding more nuanced information from the `timing` object, however I wanted to point out that if my understanding is correct, this wouldn't surface any 'queuing' time, at least in the manner that dbt Cloud defines queuing.  Are you using queuing to describe compiling, or in the dbt Cloud sense?

**Comment by kaufmannie** [comment]
Ah apologies, I think I am mistaken here. I was talking about 'queuing' on the Snowflake side. Within the Snowflake side, there is compilation, queuing and execution happening on some of our queries. My understanding is that on the Snowflake side a query is compiled, queued (if needed) and then executed. Most of the time in our instance, when queuing is happening on the Snowflake side it is because the warehouse being used is overloaded because too many other queries are already executing.  

I initially was thinking that the compile stage in dbt artifact data corresponded to the Snowflake side query compilation. In this way, any gap between the compilation "ended_at" and query execution "started_at" would be queued. But dbt does its own compilation of the model files in the project. So dbt artifact data is presumably actually the dbt project model compilation time (before sent at all to snowflake), and Snowflake compilation time is separate. So then the dbt artifact "execution" stage would be combined compilation/queuing/execution on Snowflake side. 

With that said, I do not believe adding these fields will actually allow us to get the insight I initially described. Apologies for the confusion. I will eventually dig into this further to try and confirm if I am now understanding correctly. But I am also happy to close this issue in the meantime. Let me know if that makes sense! And please let me know if you have any additional comments/thoughts.

**Comment by jaypeedevlin** [comment]
Understood, and no apologies required!  I actually did some query benchmarking a few months ago, and from that I understand that dbt doesn't actually even have an accurate (as far as Snowflake is concerned) time for the overall query runtime.  If you want the real stats, you unfortunately have to go to Snowflake and not rely on anything from dbt.

Edit: as an aside, where are the other queries being run from?  Generally I would set up dbt to have it's own warehouse so that it's not conflicting with compute from other layers (eg BI).
