### ISSUE TITLE
Add support for rows_affected for Snowflake

### ISSUE THREAD

**Issue by iribarnesy** [brooklyn-data/dbt_artifacts#196]
Hi,

It seems that the rows_affected data is available since dbt-snowflake v1.2.0 (cf. [release notes](https://github.com/dbt-labs/dbt-snowflake/releases/tag/v1.2.0))

It would be great to add it, in the same way as for BigQuery 😃
Thanks in advance

**Comment by jaypeedevlin** [comment]
Hey @iribarnesy thanks for the request — this seems like it should be a straightforward addition.  Is this something you'd be interested in contributing?

**Comment by iribarnesy** [comment]
Hey @jaypeedevlin, yes I would like to. So I would need access to the repo to push my branch

**Comment by bhratkapoor** [comment]
Hi @iribarnesy , When we can expect row_affected value being populated in MODEL_EXECUTION table in snowflake. Currently it's blank for every model execution
