### ISSUE TITLE
Move pages to GitHub Actions + build only on release.

### ISSUE THREAD

**Issue by jaypeedevlin** [brooklyn-data/dbt_artifacts#200]
Currently we rebuild pages on every merge, rather than release, which means that it's out of sync with the current release often.

My proposal is that we move this to a GHA, potentially remove the `docs` dir, instead getting GHA to do a `dbt docs generate` and then serve up the docs.

Curious to get others' thoughts on moving this

**Comment by NiallRees** [comment]
Sounds great @jaypeedevlin, the docs right now are actually just manually generated by me, which means they are nearly always outdated.

**Comment by jared-rimmer** [comment]
I've had an initial go at putting a workflow together in [this branch](https://github.com/brooklyn-data/dbt_artifacts/blob/add-actions-workflow-for-publishing-dbt-docs-on-release/.github/workflows/ci_publish_docs_on_release.yml).

Let me know if this is what you had in mind. Happy to test it by changing the logic to something other than on release.

**Comment by NiallRees** [comment]
Merged your branch and all working well, thanks @jared-rimmer !!
