### ISSUE TITLE
Dynamic database and schema targets

### ISSUE THREAD

**Issue by PeteCorbettWS** [brooklyn-data/dbt_artifacts#201]
We are looking to dynamically alter the dbt_artifacts target database based on the current profile to split out 'dev' logs from 'prod' logs to separate dbs

These target databases are different from the what is defined in profiles.yml

I'm fairly new to dbt and very new to dbt_artifacts but I can't see a way to do this via the dbt_artifcats_database project variable

One possible option would be to allow for optional database (and schema) params for the upload_results macro which would override dbt_artifacts_database var (and target.database) and allow for something like this 

**dbt_project.yml**
```
on-run-end:
 "{{ dbt_artifacts.upload_results(results,'STAGING' if target.name == 'managed' else 'SANDBOX') }}"
```
**upload_results snippet:**
```
{% macro upload_results(results,database=none,schema=none) -%}
    {% if execute %}
        {% if results != [] %}
            {% do log("Uploading model executions", true) %}
            {% set src_dbt_model_executions = source('dbt_artifacts', 'model_executions') %}
            {% set content_model_executions = dbt_artifacts.upload_model_executions(results) %}
            {{ dbt_artifacts.insert_into_metadata_table(
                database_name=database or src_dbt_model_executions.database,
                schema_name=schema or src_dbt_model_executions.schema,
                table_name=src_dbt_model_executions.identifier,
                content=content_model_executions
                )
            }}
```
If I'm missing something and this is already possible or there is a better way I'm keen to hear otherwise happy to contribute

**Comment by jaypeedevlin** [comment]
Hi Pete!

The work done in #188 actually makes the source tables dbt objects, which means they can use custom databases and will also respect `generate_database_name()` if you use it.  I'm hoping we'll cut a new version including that sometime in the next week.

**Comment by PeteCorbettWS** [comment]
Great! thanks Josh I'll key an eye out for it
