### ISSUE TITLE
Missing step in README quick start to create artifacts tables 

### ISSUE THREAD

**Issue by tfayyaz** [brooklyn-data/dbt_artifacts#202]
Just testing version 1.20 and it appears the README quick start  instructions are missing an important step to create the artifacts tables

I had to run the following command after `dbt deps` and before `dbt run` to make it work

```
dbt run-operation create_dbt_artifacts_tables --var '{dbt_artifacts_create_schema: false}'
```

**Comment by NiallRees** [comment]
Hi @tfayyaz - we're preparing a 2.0.0 release which will go out today which no longer requires this step. Sorry for the confusion!
