### ISSUE TITLE
Skipped models in snowflake result in "Numeric value '' is not recognized" error on upload_model_executions

### ISSUE THREAD

**Issue by warner-s** [brooklyn-data/dbt_artifacts#219]
First, thanks for making this great package available!!

After upgrading dbt_artifacts from 1.2.0 to 2.1.0 with (dbt version: 1.2 on Snowflake), upload_model_executions fails if there is a skipped model in the run results.

dbt logs error message:
`12:26:12  Running 1 on-run-end hook
12:26:12  Uploading model executions
12:26:13  Database error while running on-run-end
Database Error
  100038 (22018): Numeric value '' is not recognized Code: 10003`

When a model is skipped model.adapter_response.rows_affected is undefined and results in: `'',`

Changing the following:
`{% macro snowflake__get_model_executions_dml_sql(models) -%}`
...
`'{{ model.adapter_response.rows_affected }}', {# rows_affected #}`

to something like
`
{{ model.adapter_response.rows_affected or "null" }}, {# rows_affected #}
`
without single quotes and handling the undefined rows_affected should address the error.

This appears to be related to the following:
Issue 196: [Add support for rows_affected for Snowflake](https://github.com/brooklyn-data/dbt_artifacts/issues/196)
PR 208: [Add rows_affected column for snowflake](https://github.com/brooklyn-data/dbt_artifacts/pull/208)

**Comment by NiallRees** [comment]
I believe this should be resolved by https://github.com/brooklyn-data/dbt_artifacts/pull/217/files which is now released in 2.1.1. Let me know if you still encounter this!
