### ISSUE TITLE
Upgrade from v1 to v2 leads to errors in row appending

### ISSUE THREAD

**Issue by hc-dinarak** [brooklyn-data/dbt_artifacts#226]
**Current behavior**

We are using Snowflake.
Our current dbt version is 1.2.2.

When upgrading the version of the dbt_artifacts package from v1 to v2 (specifically upgrading from 1.0.0b1 to 2.0.0):
1. I ran the dbt_artifacts models. The new columns were added to the existing tables, but not where the code for them specified they would go in the order of columns: they all were appended as last columns in the data.
2. Tried to do a `dbt run` on a model to see if the dbt artifacts source tables would populate. Got an error that showed me that the data was trying to populate based on the order of columns in the dbt_artifacts code, into the table where the data was organized as described in point 1. E.g. for [model_executions](https://github.com/brooklyn-data/dbt_artifacts/blob/main/models/sources/model_executions.sql): the column `run_started_at` was populating into `was_full_refresh` column in the data, and the error was "`[datetime value]` in not a boolean". 

Unfortunately I did not collect the error messages / screenshots.

**Steps to reproduce**
1. Run dbt_artifacts 1.0.0b1 on a Snowflake warehouse and make sure all the source tables are produced:

- model_executions
- seed_executions
- snapshot_executions
- test_executions
- exposures
- models
- seeds
- sources
- tests
- invocations

2. Do a `dbt run` on one or more models in your dbt project
3. Upgrade the version of dbt_artifacts to 2.0.0 
4. Run dbt_artifacts models
5. Do a `dbt run` on one or more models in your dbt project
6. Observe the error message.

**Comment by glsdown** [comment]
Hi @hc-dinarak .

Thanks for reaching out, and apologies for how long it has taken for someone to get back to you.

I was just wondering whether this is still an issue for you, or whether you were able to resolve it? If you weren't able to resolve it, did you follow the instructions available in the [README](https://github.com/brooklyn-data/dbt_artifacts#upgrading-from-1x-to-200) regarding updating from v1 to v2?

Thanks, and apologies again for the delay.

**Comment by glsdown** [comment]
As I haven't heard anything back, I'm going to close this issue now. Please feel free to reopen it though if you are still facing the same issues.
