### ISSUE TITLE
BigQuery - 404 Not found

### ISSUE THREAD

**Issue by lanchett** [brooklyn-data/dbt_artifacts#231]
Hi,
We are experiencing that the on-run-end hook is trying to send a query to BigQuery, inserting data to a table that does not yet exist.

We can see that it sends a query to BigQuery, but this fails as the table does not already exist. I assume we're not supposed to create the table and schema beforehand (no information about this is given in the quickstart).

The error returned to dbt, directly from BigQuery:
_404 Not found: Table "<our_project:our_dataset>".model_executions was not found in location EU_

**Worth mentioning** - The profile used has sufficient rights to create new tables within this dataset. 

**_Query that BigQuery tries to run (which looks ok in my opinion) :_**

    
        /* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "xxx", "target_name": "xxx", "connection_name": "master"} */
        
        insert into our_project.our_dataset.model_executions
        VALUES
        
        
        
        (
            'c6e11536-4c12-497b-8e84-89b1b65bd3e8', 
            'model.xxx.xxx', 
            '2022-10-26 13:06:30.837610+00:00', 
            False, 
            'Thread-1', 
            'success',            
                                   
                        '2022-10-26 13:06:35.238630', 
                             
                                 
                        '2022-10-26 13:06:40.023520', 
                                   
            

            4.786630868911743, 
            safe_cast('76637' as int64),
            safe_cast('16114509' as int64),
            'table', 
            'xxx', 
            'xxx' 
            )`

**Comment by charles-astrafy** [comment]
HI @lanchett,

To initialize the different tables required by this package, you can run the following command:

`dbt run --select pacakage:dbt_artifacts`

**Comment by calkan-cue** [comment]
This is  compiled state of `stg_dbt__seed_executions.sql` and giving syntax issue in bigquery @lanchett have you seen something like that? 

```with base as (

    select *
    from `dlake`.`dbt_artifacts_source`.`seed_executions`

),

enhanced as (

    select
        
    to_base64(md5(CAST(coalesce(cast(command_invocation_id as STRING), '') || '-' || coalesce(cast(node_id as STRING), '') as STRING))) as coalesce(cast(command_invocation_id as STRING), '') || '-' || coalesce(cast(node_id as STRING), '')_hash
 as seed_execution_id,
        command_invocation_id,
        node_id,
        run_started_at,
        was_full_refresh,
        

  
    split(
        thread_id,
        '-'
        )[safe_offset(1)]
  

 as thread_id,
        status,
        compile_started_at,
        query_completed_at,
        total_node_runtime,
        rows_affected,
        materialization,
        schema, -- noqa
        name,
        alias
    from base

)

select * from enhanced
```



Note: This is not the only one but I am writing this one as a sample

**Comment by glsdown** [comment]
Hi @lanchett .

It looks like the issue you were having has been kindly resolved by @charles-astrafy , so I am going to close this issue. However, please feel free to reopen it and let me know if not.

Fwiw, I have added additional instructions in PR #297 which will hopefully address the lack of documentation around how to build the tables prior to using the post-run hook too - thank you for your feedback on this.

@calkan-cue it looks like your question may be related to something slightly different. Please could you raise a separate issue with details of what error messages you are seeing, so that I am able to help you to debug it? Thanks!
