### ISSUE TITLE
Add target column names to all insert into statements

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbt_artifacts#240]
Currently we don't specify the columns to insert new data into, we just rely on the column ordering. That feels brittle, and it also means that we have to always append new column to the list of columns in the insert clauses, vs putting them in the middle, which might sometimes be preferred.

DBX insert docs: https://docs.databricks.com/sql/language-manual/sql-ref-syntax-dml-insert-into.html
Snowflake insert docs: https://docs.snowflake.com/en/sql-reference/sql/insert.html
BigQuery insert docs: https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax

**Comment by glsdown** [comment]
This has also been raised in #305 , where @seub has kindly offered to take it on.

**Comment by glsdown** [comment]
Closing this so it can all be kept track of in a single issue.
