### ISSUE TITLE
Error when upload results with model having vars

### ISSUE THREAD

**Issue by Hoanglinh1201** [brooklyn-data/dbt_artifacts#246]
Hi,

I have an issue while using dbt 1.3 and dbt artifacts 2.2. The `dbt_artifacts.upload_results(results)` throw errors when my invocation has vars in it e.g I ran this `dbt run --select mymodel --vars "{'daterange_start':'2022-11-14', 'daterange_end':'2022-11-14'}"`

Snowflake errors said this is an invalid insert, because of the single quote.
![Screenshot 2022-11-15 at 11 52 59](https://user-images.githubusercontent.com/22580647/201902246-f81b9bf4-4a7b-4757-930e-72486763ce92.png)

![Screenshot 2022-11-15 at 11 51 16](https://user-images.githubusercontent.com/22580647/201901862-055e81c9-d0b3-4f80-923b-b5990089c888.png)

Is there a way to fix it already?

**Comment by nhrebinka** [comment]
@Hoanglinh1201  I have seen a similar comment before. It does fail when dbt runs with parameters. Do you have a query that is failing? I can take a look when I have some free time.

**Comment by smitsrr** [comment]
The fix for this was pushed yesterday and released in 2.2.1. 
I had the same issue and it's because the quotes within that method of passing vars wasn't being escaped.

**Comment by glsdown** [comment]
Hi @Hoanglinh1201 thanks for reaching out and sorry it's taken so long to get back to you. Thanks to @smitsrr for providing you with more details, and to @nhrebinka for offering to help. It sounds like this has now been resolved, so I'm going to close this issue, but please feel free to re-open it and let me know if that's not the case.
