### ISSUE TITLE
Error: materializations inherit project materializations

### ISSUE THREAD

**Issue by smitsrr** [brooklyn-data/dbt_artifacts#251]
the package 'dbt_project.yml' file specifies several default values for models, but this can be overridden by existing configurations in the project `dbt_project.yml` file. 

This is a brittle configuration setup and I would suggest explicit configs in the model files. 

While technically not DRY, it is more robust inside a package.

**Comment by NiallRees** [comment]
Hi @smitsrr, per the [dbt documentation](https://docs.getdbt.com/docs/build/packages#configuring-packages):
> Configurations made in your dbt_project.yml file will override any configurations in a package (either in the dbt_project.yml file of the package, or in config blocks).

We've set the materializations in the `dbt_project.yml` currently, the behaviour of which is the same as setting them in the model files themselves. We advise against setting configuration globally in the user project's `dbt_project.yml` as it causes an override. We can't get around this behaviour unfortunately!
