### ISSUE TITLE
Tags field not included in dim_dbt__exposures

### ISSUE THREAD

**Issue by ljones9119** [brooklyn-data/dbt_artifacts#253]
Hi

Exposure tags aren't being written to dim_dbt__exposures?

Is it possible to include tags in this model?

**Comment by glsdown** [comment]
HI @ljones9119 . Thanks for reaching out and apologies for the delay getting back to you. I've created a PR #301 which adds the tags field to the exposures table, so this will hopefully resolve your issue.
