### ISSUE TITLE
Trying to insert into tables before they have been created

### ISSUE THREAD

**Issue by dgreen161** [brooklyn-data/dbt_artifacts#256]
The artifacts package is trying to insert into the source models before they've been created. We are running v2.0.0 currently but I can't see any change in behaviour with the later releases of the package. 

**What we are observing**
When in dev, the package is trying to insert tables called `dbt_dgreen_dbt_artifacts.model_executions` etc. When running in UAT/Prod, the tables already exist (potentially as a result of fixing the issue before or as part of the migration from 1.something to v2.0.0) so this issue isn't appearing.

When in dev, this is failing the run as the tables don't exist at the time of insertion. Ideally the package would do something along the lines of `create table if not exists` before the insertion.

**Current Workaround**
In each of the dev environments, we are recommending internally to run `dbt run -s package:dbt_artifacts` which creates the empty tables.

**Environment**
DB: BigQuery
Env: Both Cloud and Core

**Comment by jaypeedevlin** [comment]
> Ideally the package would do something along the lines of create table if not exists before the insertion.

If you do a 'full' `dbt run` this will happen, but if in dev folks are running ad-hoc runs only, the problem will occur. Your workaround is how we would recommend things would work, so I'd not call it a workaround as much as BAU, but another approach is to (per the readme):

> (We recommend adding a conditional here so that the upload only occurs in your production environment, such as `on-run-end: "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"`)

Which solves the problem at the expense of not creating artifacts for dev environments, which probably don't need them anyway.

**Comment by dgreen161** [comment]
Thanks @jaypeedevlin, it seems fair to only push them in prod environments so I'll follow your recommendation. Thanks
