### ISSUE TITLE
surrogate_key is replaced by generate_surrogate_key in dbt utils v1

### ISSUE THREAD

**Issue by joellabes** [brooklyn-data/dbt_artifacts#257]
I just noticed this file: 
https://github.com/brooklyn-data/dbt_artifacts/blob/21062c908256e554355f330ed1d1af7b1d86d2e9/macros/surrogate_key.sql#L1-L5

As of dbt Core v1, surrogate_key was replaced by generate_surrogate_key which [behaves differently around null handling](https://docs.getdbt.com/guides/migration/versions/upgrading-to-dbt-utils-v1.0#changes-to-surrogate_key). 

Some options: 
- Dependency resolution is much easier in a post-v1 world, because other packages shouldn't be pinning to individual minor versions of utils. You could go back to importing utils and changing to generate_surrogate_key (for Core 1.3 installations and higher)
- You could make a copy of the null-aware macro and check for the `surrogate_key_treat_nulls_as_empty_strings` variable so that your behaviour is consistent
- You could do nothing; I imagine that a) no one else is generating surrogate keys based on your columns, and b) they don't contain null values anyway, so there will be no difference!

**Comment by glsdown** [comment]
Hi @joellabes . Thanks for flagging this (and sorry it's taken so long to get to it).

We've gone for the second approach for the time being in PR #298 , and will reconsider whether we ought to go with the first at a later date. Thanks again for flagging.
