### ISSUE TITLE
Bug: apostrophe in a meta config breaks the models insert sql statement

### ISSUE THREAD

**Issue by jameshellfeier** [brooklyn-data/dbt_artifacts#258]
The insert-statement for `database.schema.models` fails due to an apostrophe in a meta config.

dbt version: 1.3.1
python version: 3.8.9
dbt-artifacts version: 2.2.2

Offending record:

```
insert into database.schema.models
        select
            $1,
            $2,
            $3,
            $4,
            $5,
            $6,
            parse_json($7),
            $8,
            $9,
            $10,
            $11,
            parse_json($12),
            parse_json($13),
            $14
        from values
            (
                'e90c5150-d2d7-4d36-9e2d-c14efe993576', 
                'model.dbt_configs.sql_model', 
                '2022-12-21 21:41:38.496786+00:00', 
                'database', 
                'user', 
                'sql_model', 
                '[]', 
                'dbt_configs', 
                '☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺_model.sql', 
                '☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺', 
                'view', 
                '[]', 
                '{"meta_field": "description with an ' apostrophe"}', 
                'sql_model' 
            )
```

Example SQL model and .yml file:
[sql_model.txt](https://github.com/brooklyn-data/dbt_artifacts/files/10281729/sql_model.txt)
[sql_model_yml.txt](https://github.com/brooklyn-data/dbt_artifacts/files/10281792/sql_model_yml.txt)

**Comment by jameshellfeier** [comment]
This is happening with a database connection to Snowflake.

**Comment by glsdown** [comment]
HI @hellsfeier . Thanks for raising this issue, and I'm really sorry for the delay in getting back to you.

I have a PR currently open that will hopefully help resolve this issue.
