### ISSUE TITLE
Escape quotations when loading `invocations.dbt_custom_envs`

### ISSUE THREAD

**Issue by waligob** [brooklyn-data/dbt_artifacts#263]
Affected version(s): `2.2.2`

When loading the `invocations` source, the column `dbt_custom_envs` [is loaded with the value](https://github.com/brooklyn-data/dbt_artifacts/blob/21062c908256e554355f330ed1d1af7b1d86d2e9/macros/upload_invocations.sql#L116) `parse_json('{{ tojson(dbt_metadata_envs) }}') {# dbt_custom_envs #}`. This can cause syntax errors in the compiled SQL when there are quotations in `dbt_metadata_envs`, such as in the following instance:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/93673562/217048621-ed79e7ad-5ca4-41bb-bda8-c8860ce9efa9.png">

The desired behavior would be for the package to appropriately handle quotation marks when they appear in the `dbt_metadata_envs` variable without raising syntax errors.

https://github.com/brooklyn-data/dbt_artifacts/blob/21062c908256e554355f330ed1d1af7b1d86d2e9/macros/upload_invocations.sql#L116

**Comment by glsdown** [comment]
Hi @waligob. Thanks for raising the issue and apologies for how long it has taken to get back to you.

I've raised a PR #299 that should resolve this issue.
