### ISSUE TITLE
V2.2.2 Syntax Error in creating the Stage tables in surrogate key macro for Snowflake Plugin

### ISSUE THREAD

**Issue by ManjariManokar** [brooklyn-data/dbt_artifacts#265]
There is an additional AS causing SYNTAX error in SQL getting generated using **dbt_artifacts.surrogate_key** macro. This prevents the **staging table creation in snowflake plugin**
![image](https://user-images.githubusercontent.com/18352726/218528004-f87b7e26-a5a7-484e-8169-51c2cbd7fae2.png)

![image](https://user-images.githubusercontent.com/18352726/218529258-49d846bb-b993-455d-8eed-2e11368046b3.png)

**Comment by glsdown** [comment]
Hi @ManjariManokar .

Thanks for raising this issue and apologies for how long it has taken to get back to you. I was unable to replicate this exact example locally, but it did prompt me that the surrogate key macro we were using is now out of date, so I have created a PR to update it to the latest version, which should resolve this issue for you.

**Comment by ManjariManokar** [comment]
Thank you for your response
