### ISSUE TITLE
Feature Request: Store Snowflake warehouse associated with node-run

### ISSUE THREAD

**Issue by samLozier** [brooklyn-data/dbt_artifacts#266]
I'm new to this package so, so if this already exists, please disregard.

We have a few fairly large dbt projects with ~300 models in each one. We make regular use of model-specific warehouse overrides to speed up the project and save money. I was hoping to use this package to identify nodes that would be good candidates for a warehouse increase or decrease to speed up overall run time by comparing run time with warehouse size. If i'm not mistaken, warehouse size is not currently being logged by this package. 

For an example use case: 
I have a model that runs on a L warehouse, but has a mean run-time of 3 seconds. It could be run on a smaller warehouse without meaningfully slowing down the overall run. 
I have another model that's being run on a L that takes >5 minutes to run, it could be bumped to an XL or 2XL and I may even save money by doing so because the speedups are sometimes not linear. 

I'm open to creating a PR to add this functionality if it's a needed/welcome change.

**Comment by glsdown** [comment]
Hi @samLozier thanks for reaching out, and apologies it's taken a while to get back to you.

Unfortunately, the warehouse that is used isn't something that is available for us to return. To be able to include it, it would need to be added into the `dbt-snowflake` [adapater response](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L55). If you wanted to get involved, you can see how additional values are returned within the BigQuery adapter [here](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/connections.py#L90) and use that to open a PR on the `dbt-snowflake` project.

If you get it added, please do feel free to also create a PR here with the new field in - we are always open to contributions.

**Comment by samLozier** [comment]
I ended up making an internal tool that solves for this problem by modifying the snowflake querytag at runtime to add information about model name, warehouse name, invocation id, username and a few more pieces of information. I also setup an incremental model that queries the snowflake activity table for information about queries related to the current project.  That incremental model is triggered via a post run hook. 

I don't plan to publish my solution, but hopefully that's enough of a roadmap for someone else trying to answer the same question.

**Comment by glsdown** [comment]
Thanks for sharing your workaround. I'll close this issue as you have solved what you need to.
