### ISSUE TITLE
docment "source" models

### ISSUE THREAD

**Issue by dave-connors-3** [brooklyn-data/dbt_artifacts#267]
Users of both `dbt_artifacts` and `dbt_project_evaluator` get issues in the `fct_undocumented_models` check for models from this package! Specifically, the `source` models do not have descriptions, and therefore fail this check .

Adding descriptions would resolve this issue in the short term. Some work to be done on our side (i.e. project evaluator team) to restrict checks on models from other packages completely!

[Source thread in dbt slack](https://getdbt.slack.com/archives/CU4MRJ7QB/p1676661048963109)

**Comment by glsdown** [comment]
Hi @dave-connors-3 , thanks for raising and apologies for how long it's taken to get back to you. I've created a PR which will hopefully resolve this in a future release.
