### ISSUE TITLE
Feature request: Add source/fact table for source-freshness executions 

### ISSUE THREAD

**Issue by emilyhawkins-gg** [brooklyn-data/dbt_artifacts#272]
It would be great to have a table like `fct_source_freshness_executions` to have the metadata for source freshness runs and statuses (like when sources fail freshness tests)

**Comment by the-davidsn** [comment]
+1! 
Would be great to see that.

**Comment by glsdown** [comment]
Hi @emilyhawkins-gg and @DavidHuegel .

Thanks for raising this, and apologies for the delay in getting back to you. This is something we'd love to support, but are waiting for an upstream change in dbt core that would allow us to do it currently. Once [this](https://github.com/dbt-labs/dbt-core/issues/5609) has been resolved, we'll definitely look to include it.

Related PR: #166

**Comment by glsdown** [comment]
I'm closing this issue so that this can be tracked in a single place - #166
