### ISSUE TITLE
[Feature]: Have a Snowflake query_id (query_history) inside dbt_artifacts entities

### ISSUE THREAD

**Issue by LucasMMota** [brooklyn-data/dbt_artifacts#283]
## Overview

I'm struggling trying to establish a link between the tables query_history (in Snowflake) and the dbt_artifacts tables, but couldn't find a key (or keys) to link them.

For models monitoring in Snowflake it is necessary to have the queries IDs stored inside the dbt_artifacts tables (as we have for schema name, model name, etc) for getting more information from the query_history entity, like the warehouse used in the query execution.

Actually I need the warehouse name for that invocation, but though in the query_id as a better approach for linking those entities and providing also other metadata.

## What problem would this solve?

Provide more information for models analysis - got from Snowflake's query_history table.

## Would you be willing to contribute?

- [ ] Yes - I'm on it!
- [X] Yes, but I'd need help getting started.
- [ ] No

**Comment by glsdown** [comment]
Hi @LucasMMota , apologies for not getting back to you on this - I thought I had sent a response, but it looks like I didn't hit send on it.

As you will see, I have recently merged a PR which adds a column into the `sources.*_executions` tables which includes the full `adapter_response`. As this varies by adapter, I haven't expanded this into the individual values within there, but the `snowflake` adapter [does include the query ID](https://github.com/dbt-labs/dbt-snowflake/blob/3be577de7086c361442599114a49b14e6289e7b3/dbt/adapters/snowflake/connections.py#L377) so you'll be able to extract this from the `adapter_response` field within those tables.

I hope this will help you to be able to link the two? It hasn't yet been released, but will be included in the next version, which we hope to have ready in the next couple of week.

**Comment by LucasMMota** [comment]
Yes, that will permit join the Snowflake and `dbt_artifacts` entities. Thank you @glsdown !
