### ISSUE TITLE
fct_dbt__critical_path.sql flatten error

### ISSUE THREAD

**Issue by bmedx** [brooklyn-data/dbt_artifacts#29]
Hi folks,

I'm attempting to get artifacts running, but I am getting the following error when I try to `dbt run --models dbt_artifacts` :

```
Database Error in model fct_dbt__critical_path (models/fct_dbt__critical_path.sql)
  000940 (22023): SQL compilation error: error line 46 at position 12
  missing required argument [INPUT] for function [flatten]
  compiled SQL at target/run/dbt_artifacts/models/fct_dbt__critical_path.sql
``` 

At a guess this is because we don't have any manifests loaded (ours are too big to fit into a single VARIANT). We were hoping to still get some value out of the package by checking model creation times, test statuses (when those land), etc. Can you take a look?

**Comment by alanmcruickshank** [comment]
I'm afraid without any manifests loaded, there's nothing to query. I'm curious, how many models do you have?

We've got around 1.2k models and this just about still works (although it is getting very slow).

I'm considering doing more of the flattening on upload - it changes the paradigm of this package quite a lot but I think is more useful for larger projects like yours. How does that sound?

**Comment by bmedx** [comment]
Thanks for taking a look! I'd like to challenge the notion that there's nothing to query without the manifests. We've worked around this by writing our own version of the plugin and still get all of the things I noted above (last model run time, frequency of model/test failure, longest model run times, etc) from just the run_results.

Our biggest project has 700 models, but 2k sources. I think flattening on upload probably makes the most sense for being able to load large manifests, but does certainly complicate things.

**Comment by NiallRees** [comment]
Hi @bmedx - this still requires the manifest to load however the latest version of the code will now flatten manifests on load which should overcome your large manifest issue. Going to close this out.
