### ISSUE TITLE
[Feature]: Freshness executions

### ISSUE THREAD

**Issue by dennysrega1ado** [brooklyn-data/dbt_artifacts#292]
## Overview

I would like to have a `SOURCE_EXECUTIONS` table showing `dbt source freshness` results.

## What problem would this solve?

The freshness "tests" are using to detect stale data in the sources.
It will be helpful to have it so we can monitor stale errors.

## Would you be willing to contribute?

- [ ] Yes - I'm on it!
- [x] Yes, but I'd need help getting started.
- [ ] No

**Comment by glsdown** [comment]
Hi @dennysrega1ado .

Thanks for raising this. This is something we'd love to support, but are waiting for an upstream change in dbt core that would allow us to do it currently. Once https://github.com/dbt-labs/dbt-core/issues/5609 has been resolved, we'll definitely look to include it.

Related PR: https://github.com/brooklyn-data/dbt_artifacts/issues/166

**Comment by glsdown** [comment]
I'm closing this issue so that this can be tracked in a single place - #166
