### ISSUE TITLE
Question - Can I select the type of data that I want the package to upload? 

### ISSUE THREAD

**Issue by NJarZe** [brooklyn-data/dbt_artifacts#304]
First of all, thank you for this! First time using it and I can already see the benefits. 

As the title says, if I am only interested in uploading the data about models and their executions (no tests, nor anything else), is there a way for me to select the type of data I want, or is it all or nothing?

**Comment by glsdown** [comment]
Hi @NJarZe . Thanks for reaching out, and I'm glad you are already reaping the benefits.

I'm afraid there is no way of restricting which models get built, and it is all or nothing. Hope this helps!
