### ISSUE TITLE
[Bug]: upload_invocations() fails on the dbt-databricks 1.5.0

### ISSUE THREAD

**Issue by henrikamnas** [brooklyn-data/dbt_artifacts#307]
## Overview
Seems the invocation_args_dict has changed so that the json parsing failes here:
'{{ tojson(invocation_args_dict) | replace('\\', '\\\\') }}', {# invocation_args #}

Let me know if there is anything I can do to help, this is a great package!

## How to reproduce
1. upgrade dbt-databricks to 1.5.0 or above
2. run any dbt command using dbt-artifacts on-run-end

## Expected behaviour

To the command to succeed with invocations data uploaded

## Environment

Results of running `dbt --version`:

```sh
# Add the results here
```
packages:
  - package: brooklyn-data/dbt_artifacts
    version: 2.3.0

**Comment by glsdown** [comment]
Hi @henrikamnas thanks for raising (and sharing your ❤️ for our package).

We are prioritising support for 1.5 now, so will be looking into this asap. The same issue has also been reported in #296 . I am hoping it will be a simple fix to do, but I can't promise on timelines at the moment I'm afraid.

**Comment by glsdown** [comment]
Hi @henrikamnas . Thanks for your patience whilst we resolved this. We have just published a release 2.4.0 which should resolve this issue. Please feel free to reopen it though if you find it doesn't solve it.
