### ISSUE TITLE
[Feature]: Add a field in the models table for the whole "config"

### ISSUE THREAD

**Issue by jsnb-devoted** [brooklyn-data/dbt_artifacts#317]
## What problem would this solve?
The [upload_models](https://github.com/brooklyn-data/dbt_artifacts/blob/main/macros/upload_models.sql) macro parses out some of the more key properties from the config like the tags and meta but the other configs you can put aren't included. In our case we provide a custom config `final_schema` that we wanted to use in the db but that isn't in the artifacts table. 

What would you all think about adding a json field with the whole config?

## Would you be willing to contribute?

- [ ] Yes - I'm on it!
- [x] Yes, but I'd need help getting started.
- [ ] No

**Comment by glsdown** [comment]
Hi @jsnb-devoted , thanks for reaching out!

We have recently merged a PR which I believe does just this #280. It includes all available fields as a JSON field called `all_results` for these tables:

- exposures
- models
- seeds
- snapshots
- sources
- tests

This column is only available in the `sources` models and has not been included in any of the staging or fact/dim tables, but hopefully would provide the detail you want. We are hoping to get a release out with this in soon.

**Comment by jsnb-devoted** [comment]
That’s perfect! Just what I was looking for. For my purposes it is fine in the source table rather than the fact/dim tables. Appreciate the quick response. We’ll keep and eye out for the release.
