### ISSUE TITLE
dim_dbt__exposures.manifest_model_id is not unique

### ISSUE THREAD

**Issue by djbelknapdbs** [brooklyn-data/dbt_artifacts#32]
The unique test for the field `dim_dbt__exposures.manifest_model_id` is failing when `depends_on_nodes` has more than one node. It seems like for this model, the depends_on shouldn't get expanded, and there should be a separate model to cross-reference exposures and their depends-on models? 

Alternately, the test should get switched to a `dbt_utils.unique_combination_of_columns` with `manifest_model_id` and `output_feeds`.

I'm glad to contribute to this if you let me know which way you want it to go - split out `output_feeds` or keep it in and switch the test.

**Comment by alanmcruickshank** [comment]
Totally agree. We've had this packaged disabled for a few weeks, just re-enabled it and got this issue! Fixing it right now :)
