### ISSUE TITLE
[Bug]: Object of type WarnErrorOptions is not JSON serializable when running dbt artifacts on dbt 1.5.0

### ISSUE THREAD

**Issue by mvdwielen** [brooklyn-data/dbt_artifacts#333]
The following error occurs when running dbt artifacts on DBT 1.5.0, the error doesn't occur if dbt artifacts runs on DBT 1.4.1 (see second part)

part 1 dbt 1.5.0
---------------------
07:45:30  Running 2 on-run-end hooks
07:45:30  1 of 2 START hook: x239.on-run-end.0 ........................................... [RUN]
07:45:30  1 of 2 OK hook: x239.on-run-end.0 .............................................. [OK in 0.13s]
07:45:30  Uploading model executions
07:45:32  Uploading seed executions
07:45:32  Uploading snapshot executions
07:45:32  Uploading test executions
07:45:32  Uploading exposures
07:45:32  Uploading tests
07:45:32  Uploading seeds
07:45:32  Uploading models
07:45:34  Uploading sources
07:45:35  Uploading snapshots
07:45:35  Uploading invocations
07:45:35  Database error while running on-run-end
07:45:36  
07:45:36  Finished running 16 incremental models, 26 view models, 7 table models, 1 hook in 0 hours 11 minutes and 25.91 seconds (685.91s).
07:45:36  
07:45:36  Completed with 1 error and 0 warnings:
07:45:36  
**07:45:36  on-run-end failed, error:**
**07:45:36   Object of type WarnErrorOptions is not JSON serializable**

part 2 dbt 1.4.1
---------------------

08:04:38  Running 2 on-run-end hooks
08:04:38  1 of 2 START hook: x239.on-run-end.0 ........................................... [RUN]
08:04:38  1 of 2 OK hook: x239.on-run-end.0 .............................................. [OK in 0.12s]
08:04:38  Uploading model executions
08:04:40  Uploading seed executions
08:04:40  Uploading snapshot executions
08:04:40  Uploading test executions
08:04:40  Uploading exposures
08:04:40  Uploading tests
08:04:40  Uploading seeds
08:04:40  Uploading models
08:04:42  Uploading sources
08:04:44  Uploading snapshots
08:04:44  Uploading invocations
08:04:45  2 of 2 START hook: x239.on-run-end.1 ........................................... [RUN]
08:04:45  2 of 2 OK hook: x239.on-run-end.1 .............................................. [OK in 0.00s]
08:04:45  
08:04:45  
08:04:45  Finished running 16 incremental models, 26 view models, 7 table models, 2 hooks in 0 hours 4 minutes and 24.53 seconds (264.53s).
08:04:45  
08:04:45  Completed successfully

**Comment by jared-rimmer** [comment]
Hi @mvdwielen. The current release does not support dbt `1.5.0` but the next one will. We're aiming to release this week
