### ISSUE TITLE
[Bug]: Environment variable DBT_ARTIFACT_STATE_PATH has been renamed to DBT_STATE

### ISSUE THREAD

**Issue by jakobfloe** [brooklyn-data/dbt_artifacts#359]
## Overview

12:31:33  [WARNING]: Deprecated functionality
The environment variable `DBT_ARTIFACT_STATE_PATH` has been renamed as
`DBT_STATE`. If `DBT_ARTIFACT_STATE_PATH` is currently set, its value will be
used instead of `DBT_STATE`. Set `DBT_STATE` and unset `DBT_ARTIFACT_STATE_PATH`
to avoid this deprecation warning and ensure it works properly in a future
release.

## How to reproduce

Simply run a job in dbt cloud.

## Expected behaviour

No warnings in system logs

## Environment

dbt cloud v. 1.5

Please paste the contents of your `packages.yml` file here:

packages:

  - package: dbt-labs/dbt_utils
    version: 1.1.1

  - package: brooklyn-data/dbt_artifacts
    version: 2.4.2
  
  - package: calogica/dbt_date
    version: 0.7.2

  - package: tnightengale/dbt_meta_testing
    version: 0.3.6

**Comment by glsdown** [comment]
Hi @jakobfloe thanks for commenting.

I believe this is related to `dbt` and not `dbt_artifacts` as in their [1.5 release](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5) they renamed some environment variables. I am not able to replicate the issue that you are having and I can't see that we use that variable anywhere. Can you search your code base to see if you explicitly use the `DBT_ARTIFACT_STATE_PATH` environment variable anywhere in your project please?

**Comment by glsdown** [comment]
I'm closing this issue as it seems like it's an upstream problem and not related to this package. Please let me know if it's been closed in error though.
