### ISSUE TITLE
[Bug]: Invalid rows_affected, bytes_processed and runtime on incremental models in current_models

### ISSUE THREAD

**Issue by Esya** [brooklyn-data/dbt_artifacts#372]
## Overview

Because of the way `dim_dbt__current_models` is written, the rows_affected, bytes_processed and total_runtime stats are wrongly reported using incremental models.

https://github.com/charles-astrafy/dbt_artifacts/blob/1bf85edceac80b1083fc42626437ebeaeaac4363/models/dim_dbt__current_models.sql#L41-L53

```sql
latest_model_stats as (
    select
        node_id
        , max(case when was_full_refresh then query_completed_at end) as last_full_refresh_run_completed_at
        , max(case when was_full_refresh then total_node_runtime end) as last_full_refresh_run_total_runtime
        , max(case when was_full_refresh then rows_affected end) as last_full_refresh_run_rows_affected
        {% if target.type == 'bigquery' %}
        , max(case when was_full_refresh then bytes_processed end) as last_full_refresh_run_bytes_processed
        {% endif %}
        , max(query_completed_at) as last_run_completed_at
        , max(total_node_runtime) as last_run_total_runtime
        , max(rows_affected) as last_run_rows_affected
        {% if target.type == 'bigquery' %}
        , max(bytes_processed) as last_run_bytes_processed
        {% endif %}
    from latest_models_runs
    where run_idx = 1
    group by 1
),
```

Because the [models are partitioned by node ID and full refresh](https://github.com/charles-astrafy/dbt_artifacts/blob/1bf85edceac80b1083fc42626437ebeaeaac4363/models/dim_dbt__current_models.sql#L30C1-L33C21), the same model ends up twice in `latest_model_stats` (with `was_full_refresh` true and false), but the full refresh almost always has more bytes processed and a longer runtime, meaning the `max(bytes_processed)` and others report the stats from the full-refresh run, not the actual latest incremental run.

### Propositions :
- Fixing the current `last_run_*` columns so they return the stats matching the true last chronological run
- Optional: Add some columns that are specific to incremental runs such as
  - `last_incremental_run_completed_at`
  - `last_incremental_run_total_runtime`
  - `last_incremental_run_rows_affected`
  - `last_incremental_run_bytes_processed`

I can fix the issue but I need to know which way we want to go with this.

## How to reproduce

1. Write any incremental model
2. Run it in --full-refresh mode
3. Run it in incremental mode 

## Expected behaviour

Actual stats of the incremental run

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.5.3
  - latest:    1.6.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.5.3 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.6.2
  - package: dbt-labs/audit_helper
    version: 0.9.0
  - package: brooklyn-data/dbt_artifacts
    version: 2.4.3
```

**Comment by glsdown** [comment]
Hi @Esya thank you for raising this, and I'm sorry for how long it's taken to respond.

This was a really excellent spot, and I think that the right approach is a combination of the two things you've suggested. Due to how long it's taken me to get back to you, I've created a PR which should fix the issue and I'll aim to get it merged asap.

**Comment by Esya** [comment]
That's awesome, thanks for handling this issue, looking forward to it being merged!
