### ISSUE TITLE
[Bug]: The latest dbt_artifacts version is not compatible with dbt 1.6.0

### ISSUE THREAD

**Issue by nhnam1105** [brooklyn-data/dbt_artifacts#373]
## Overview
The latest version of dbt_artifacts is not compatible with dbt version 1.6.0. When upgrading dbt to 1.6.0, attempting to run dbt clean and dbt deps results in an error.

## How to reproduce

- Upgrade dbt to version 1.6.0
- Run `dbt clean` to clean the project.
- Run `dbt deps` to install project dependencies.

## Expected behaviour
After running the steps above, I expected `dbt deps` to successfully install the project dependencies, including dbt_artifacts version 2.4.3, without any errors.

## Screenshots
![image](https://github.com/brooklyn-data/dbt_artifacts/assets/32213739/aeb16fdb-02f1-42a8-bb84-b001837f8877)

## Environment

Results of running `dbt --version`:

```sh
# Add the results here
Core:
  - installed: 1.6.0
  - latest:    1.6.0 - Up to date!

Plugins:
  - bigquery: 1.6.1 - Up to date!
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: "brooklyn-data/dbt_artifacts"
    version: "2.4.3"
  ...
```

**Comment by glsdown** [comment]
Sorry this took so long, but I've just published a release that should include this now.
