### ISSUE TITLE
[Bug]: The latest dbt_artifacts version is not compatible with dbt 1.7.0

### ISSUE THREAD

**Issue by JustMaris** [brooklyn-data/dbt_artifacts#401]
## Overview

The latest version of dbt_artifacts is not compatible with dbt version 1.7.0. When upgrading dbt to 1.7.0, attempting to run dbt clean and dbt deps results in an error.

## How to reproduce

- Upgrade dbt to version 1.7.0
- Run dbt clean to clean the project.
- Run dbt deps to install project dependencies.

## Expected behaviour

After running the steps above, I expected dbt deps to successfully install the project dependencies, including dbt_artifacts version 2.6.1, without any errors.

## Screenshots

![image](https://github.com/brooklyn-data/dbt_artifacts/assets/24903212/718ca131-fba9-4b5f-ad1c-b29f01e470a7)

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.7.0
  - latest:    1.7.0 - Up to date!

Plugins:
  - snowflake: 1.7.0 - Up to date!
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
...
  - package: brooklyn-data/dbt_artifacts
    version: [">=2.6.0", "<2.7.0"]
...
```

**Comment by glsdown** [comment]
Support for 1.7 has now been added into v2.6.2. Please upgrade and let me know if you are still having issues.
