### ISSUE TITLE
[Bug]: dbt-project.yml file of the dbt-artifacts 2.6.1 version excludes dbt versions 1.7.0 and above

### ISSUE THREAD

**Issue by foxmulder42** [brooklyn-data/dbt_artifacts#402]
## Overview

dbt-project.yml file of the dbt-artifacts 2.6.1 version excludes dbt versions 1.7.0 and above.
`
name: "dbt_artifacts"
version: "2.6.1"
config-version: 2
require-dbt-version: [">=1.3.0", "<1.7.0"]
profile: "dbt_artifacts"
`

## How to reproduce

-     Upgrade dbt to version 1.7.0
-     Run dbt clean to clean the project.
-     Run dbt deps to install project dependencies.

## Expected behaviour

After successful upgrade of dbt (1.7.0) and dbt-artifacts (2.6.1) I would expect to perform a dbt run -m modelname. This failes to version restrictions in the dbt-project.yml file in the lates package release. 

## Screenshots

![Screenshot 2023-11-14 14 36 07](https://github.com/brooklyn-data/dbt_artifacts/assets/107245304/5b6ce161-2121-4e67-b203-e561c7d8c311)

## Environment

Results of running `dbt --version`:
Core:
  - installed: 1.7.0
  - latest:    1.7.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.7.0 - Up to date!

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - git: https://github.com/brooklyn-data/dbt_artifacts.git
    revision: 2.6.1

  ...
```

**Comment by glsdown** [comment]
Support for 1.7 has now been added into v2.6.2. Please upgrade and let me know if you are still having issues.
