### ISSUE TITLE
Support for dbt 0.20.0

### ISSUE THREAD

**Issue by ajbosco** [brooklyn-data/dbt_artifacts#42]
Only dbt_utils 0.7.0+ is supported for dbt 0.20.0. Is it possible to upgrade this dependency to support that?

https://github.com/tailsdotcom/dbt_artifacts/blob/main/packages.yml#L3

**Comment by alanmcruickshank** [comment]
Yes, this will be supported in the `0.5.0` release

**Comment by JustMaris** [comment]
Any projected date for 0.5.0 release?

**Comment by alanmcruickshank** [comment]
Just now 😄
