### ISSUE TITLE
[Bug]: "compile_started_at" and "query_completed_at" times for test get extracted from wrong object resulting in nulls

### ISSUE THREAD

**Issue by TimWitzel** [brooklyn-data/dbt_artifacts#427]
## Overview

for the test_executions data, the two fields "compile_started_at" and "query_completed_at" are always null.

## How to reproduce

Run anything and check the test_executions.

## Expected behaviour

Both fields should be properly extracted from the run results.

## Screenshots

![image](https://github.com/brooklyn-data/dbt_artifacts/assets/61972354/0480da95-efc0-4165-9ff6-c5afd107c2c7)

## Environment

Results of running `dbt --version`:
dbt core 1.7.11, dbt artifacts 2.6.2 on databricks

## Potential Fix
![image](https://github.com/brooklyn-data/dbt_artifacts/assets/61972354/05cffd4a-aba6-4ca4-a5c7-a81b483ae0cd)
Seems like there was a copy/paste error. Changing the model.timing to test.timing (for compile started at and query completed at) fixes this. Seems like this was overlooked.

**Comment by TimWitzel** [comment]
Just saw that there is already a pull request for that: https://github.com/brooklyn-data/dbt_artifacts/pull/420

**Comment by llifoawing** [comment]
This has been fixed and latest version available on dbt Hub
