### ISSUE TITLE
[Bug]: Unable to write dbt_artifacts results to different dataset in Bigquery

### ISSUE THREAD

**Issue by kabam-blambert** [brooklyn-data/dbt_artifacts#434]
## Overview

After following the guide and trying several different things, I am not really able to get the dbt_artifacts output to wind up anywhere other than the dataset specified in profiles.yaml.

## How to reproduce

dbt-core 1.3.1 
dbt-bigquery 1.3.0
dbt_artifacts 2.6.3

Following the guide and adding the necessary:
```yaml
models:
  ...
  dbt_artifacts:
    +database: your_destination_database # optional, default is your target database
    +schema: your_destination_schema # optional, default is your target schema
    staging:
      +database: your_destination_database # optional, default is your target database
      +schema: your_destination_schema # optional, default is your target schema
    sources:
      +database: your_sources_database # optional, default is your target database
      +schema: your sources_database # optional, default is your target schema
```
to dbt_project.yml (also trying to replace +database with +project and +schema with +dataset) the views are still being added to the default dataset.

## Expected behaviour

Regular models should be written to the default project + dataset as specified in profiles.yml and dbt_artifacts models should be written to the specified project + dataset.

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.3.1
  - latest:    1.8.3 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.3.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: "1.0.0-b2"
  - package: calogica/dbt_expectations
    version: [">=0.8.0"]
  - package: brooklyn-data/dbt_artifacts
    version: 2.6.3
  ...
```
Not sure if it could be due to the outdated version of dbt we are using.

**Comment by wsargent-emcins** [comment]
@kabam-blambert I'm seeing the same issue as well on snowflake on latest in cloud.  I am looking to force the database and schema, and for me, while the database part works, the specified schema is getting appended to the target schema.

i.e.:
My project is building to dev_sandbox.mde_poc_prod
And I want artifacts to populate:
dev_dbt_artifacts.dbt_mde_poc

But instead it's trying to populate the artifacts to: DEV_DBT_ARTIFACTS.MDE_POC_PROD_DBT_MDE_POC

So the schema I am calling out in artifacts is getting appended instead of replaced.
Seems like a problem with or missing a custom generate_schema_name macro in the dbt_artifacts package.

And for me, this isn't a CI build either (full job).

**Comment by wsargent-emcins** [comment]
Follow on:
Looks like this might be "predicted" behaviour according to the readme:

```
That's because the raw tables are now managed as dbt models. Be aware of any impact that [generate_database_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-databases#generate_database_name) and [generate_schema_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas#how-does-dbt-generate-a-models-schema-name) macros may have on the final database/schema```

**Comment by wsargent-emcins** [comment]
Here's the fix: You need to create an override generate_schema_name macro, and edit the else to remove the prefix behaviour.

Keep in mind this affects all schemas in the project, so there might be some more sophisticated logic to be had here.  I tried some things, but the on-run-end hook seemed to be a bit quirky.

this fix is courtesy: 
[This medium article](https://medium.com/@jvaldiviaparra/customize-schema-in-dbt-by-overwriting-the-macro-generate-schema-name-3261d294ee3f)

```
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}

    {%- if custom_schema_name is none -%}

        {{ default_schema }}

    {%- else -%}
        {{ custom_schema_name | trim }}

    {%- endif -%}

{%- endmacro %}
```

**Comment by kabam-blambert** [comment]
@wsargent-emcins hey thanks a ton for all your help with this!

**Comment by wsargent-emcins** [comment]
You bet @kabam-blambert! One more unlock: If you want to add logic to detect the special database, you need to use `node.database` instead of `target.database`:

(I added some logging here, that is optional)

```
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}
    {%- set debug_message = '[GSN] Node: ' ~ node.name ~ ' Node Database: ' ~ node.database ~ ' Target Database: ' ~ target.database ~ ' Default Schema: ' ~ default_schema ~ ' Custom Schema: ' ~ custom_schema_name%}

    {# If the node database is the dev_dbt_artifacts database, don't prefix the custom schema #}
    {%- if node.database == 'dev_dbt_artifacts' -%}
        {{ log(debug_message, info=True) }}
        {{ log('[GSN] Detected Artifacts Database Detected. Using custom_schema_name', info=True) }}
        {{ custom_schema_name | trim }}

    {# If the custom_schema_name is empty, use the default schema from the job or environment #}
    {%- elif custom_schema_name is none -%}
        {{ default_schema }}

    {# If there is a specific schema called out in the model YAML or model config block, then append the default schema and use that schema (default dbt behaviour) #}
    {%- else -%}
        {{default_schema}}_{{ custom_schema_name | trim }}

    {%- endif -%}

{%- endmacro %}
```
