### ISSUE TITLE
Wrapper macro to upload artifacts by command

### ISSUE THREAD

**Issue by djbelknapaw** [brooklyn-data/dbt_artifacts#45]
Right now users upload artifacts by specifying which artifacts to upload (manifest, catalog, etc.) That can be a pain to remember which artifacts to upload after which dbt command.

I'd be interested in seeing a wrapper macro so I could upload artifacts via:
```
dbt run-operation upload_dbt_artifacts_by_command --args '{command: run}'
```
This would just be a convenience feature that would map the command to the appropriate artifacts and run the existing macro to upload them. You could still upload specific artifacts using the existing macro.

I'm open to contributing if you're interested in adding this and don't want to spend the time on your end.

**Comment by NiallRees** [comment]
Hey @djbelknapaw - this would be a valuable contribution! Please feel free to put a PR together.

**Comment by alanmcruickshank** [comment]
I might pick this up along with the solution for #62 .

**Comment by NiallRees** [comment]
We've been busy reimplementing the package, removing the use of artifacts altogether. The new version uses the graph and results context variables. We'd be grateful for any feedback on the first beta release: https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1
