### ISSUE TITLE
Test failure in fct_dbt__model_executions

### ISSUE THREAD

**Issue by djbelknapaw** [brooklyn-data/dbt_artifacts#46]
The Unique test on this model is failing when I run on dbt Cloud:
```
Failure in test unique_fct_dbt__model_executions_model_execution_id (models/schemas.yml)
```

I suspect this is a result of two things, but it might still need more digging.
1)  If I run all the commands (seed, run, test, etc.) and upload artifacts after each one following the instructions on this package's home page, I end up with two manifests with the same dbt_cloud_run_id (one from seed and one from run) which in turn creates two records per node in `dim_dbt__models`. 
1) Using the `dbt_cloud_run_id` environment variable for this join in `fct_dbt__model_executions`:
```

model_executions_with_materialization as (

    select
        model_executions_incremental.*,
        models.model_materialization,
        models.model_schema,
        models.name
    from model_executions_incremental
    left join models on
        (
            model_executions_incremental.command_invocation_id = models.command_invocation_id
            or model_executions_incremental.dbt_cloud_run_id = models.dbt_cloud_run_id
        )
        and model_executions_incremental.node_id = models.node_id

),
```

This doesn't immediately get caught if you use dbt Cloud for ci because the **first** `dbt run` doesn't have the artifacts from itself, so only the manifest from `dbt seed` exists the first time dbt_artifacts runs. Any subsequent run fails.

A simple workaround is not to upload manifest after `dbt run` (or seed, but I figure it's good to upload it at the earliest possible step), but I'm not sure if that breaks anything later on in this package? If not, it might be a simple documentation fix to take manifest out of that step. I tested this and it resolves the failing test, I just don't know if this loses any detail I should have.

Another possible solution would be to `coalesce(dbt_cloud_run_id, command_invocation_id)` into a single field so when the cloud_run_id is present it gets used, otherwise it falls back on the command_invocation_id. This might be a bigger task throughout the package, but I think would have the side effect of solving this issue.

**Comment by callumwebb** [comment]
I've also just run into this problem. The simple workaround mentioned by djbelknapaw is helpful but doesn't resolve it for historical records that have already been uploaded.

I'm currently weighing up archiving historical data and truncating the `dbt_artifacts_table` in conjunction with the workaround to get tests passing again.

**Comment by NiallRees** [comment]
We've been busy reimplementing the package, and this shouldn't be a problem any more! We'd be grateful for any feedback on the first beta release: https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1
