### ISSUE TITLE
Proposal: Add exposure, source, and model metadata to `dim_` tables

### ISSUE THREAD

**Issue by stkbailey** [brooklyn-data/dbt_artifacts#48]
I would like to be able to leverage the package to present data source information in downstream tools, including object descriptions, tags, and metadata.

Proposal would be to add the following columns to `dim_dbt__sources`, `dim_dbt__models` and `dim_dbt__exposures`:

- meta (variant type)
- description (text)
- tags (array type)

Has this been considered before? I may have some time to contribute this if it's desired.

**Comment by stkbailey** [comment]
After playing around with the package for a while, I am guessing that the reason for not including this is due to a potential explosion in the size of the tables over time since the descriptions may be too large. Perhaps having a table with the `latest_metadata` for each `node_id` would make this feasible.

**Comment by NiallRees** [comment]
Resolved by https://github.com/brooklyn-data/dbt_artifacts/pull/66
