### ISSUE TITLE
Proposal: Give seed and snapshot executions their own `fct_` models

### ISSUE THREAD

**Issue by stkbailey** [brooklyn-data/dbt_artifacts#49]
It appears that nodes where `resource_type = 'seed'` and `resource_type = 'snapshot'` are excluded from this package, although these are important operations to track. I would propose adding these as additional `dim_` and `fct_` tables to complement the existing `test_executions` and `model_executions` models.

The reason these are currently being exclude is due to this line in `stg_dbt__model_executions`:

```
dbt_run as (

    select *
    from run_results
    where data:args:which = 'run'

),
```

Filtering on the `run` argument will filter out `dbt snapshot` and `dbt seed` calls.

**Comment by NiallRees** [comment]
Resolved by https://github.com/brooklyn-data/dbt_artifacts/pull/66
