### ISSUE TITLE
dbt invocation_id changes on upload_dbt_artifacts

### ISSUE THREAD

**Issue by DVAlexHiggs** [brooklyn-data/dbt_artifacts#53]
When running:

`dbt run-operation upload_dbt_artifacts ...`

This causes `manifest.json` to get a different `invocation_id`. This is intended dbt behavior and it makes sense, however it does have the side-effect of causing manifests and run-results that would usually be join-able on `invocation_id` to not join.

I re-named the manifest file I wanted to retain the `invocation_id` for prior to running the upload operation and uploaded the renamed version, using some updates in Snowflake to change the PATH and ARTIFACT_TYPE back to `manifest.json` and `manifest.json.gz` accordingly. 

I'm not aware of any ways around this if uploading locally using the dbt cli. I will probably put this in a pipeline and upload it via AWS S3 and Snowflake (as per Option 2 on the README)

I think that this should at least be documented or noted somewhere because this took me a few days of headache and I think it will be worth saving anyone else the trouble in future.

Thanks!

**Comment by NiallRees** [comment]
Hey Alex, you're right that this is confusing. Currently, joins attempt to match on either `invocation_id` or `dbt_cloud_run_id`, see [here](https://github.com/tailsdotcom/dbt_artifacts/blob/main/models/incremental/fct_dbt__model_executions.sql#L39-L40). A couple of ideas to overcome this while still being able to use the `upload_dbt_artifacts` run-operation:
1. Use an [environment variable](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var#custom-metadata) which can be used to match the `manifest.json` to the `run_results.json`. You'd have to come up with a way to make sure the value was changed whenever you modified the project, and add the environment variable as an additional join key in the models. A PR would be very welcome for this, perhaps the env var could be called `DBT_ENV_CUSTOM_ENV_DBT_ARTIFACTS_JOIN_KEY`.
2. (Change to dbt-core required) A new metadata key in `run_results.json` and `manifest.json` is added as a hash of the entire project. This is definitely the best solution as it wouldn't require any manually configured environment variables.

**Comment by jmak123** [comment]
Another effect of this issue is that in dbt Cloud where one job has multiple `dbt run`s that need to have artifacts recorded, we can't reliably identify the pairs of eg. manifest + run_results.

**Comment by NiallRees** [comment]
> Another effect of this issue is that in dbt Cloud where one job has multiple `dbt run`s that need to have artifacts recorded, we can't reliably identify the pairs of eg. manifest + run_results.

In this instance, you could actually join any of the `manifest.json`s which match on the `dbt_cloud_run_id`, as the `manifest.json` generated by each `dbt run` command within the same dbt Cloud run will be identical. It would require a couple modifications to the package to deduplicate manifests on the `dbt_cloud_run_id`.

**Comment by alanmcruickshank** [comment]
@NiallRees - I think that #81 solves this. If you agree can you close this issue?

**Comment by NiallRees** [comment]
> @NiallRees - I think that #81 solves this. If you agree can you close this issue?

I'm not sure that it does, but the specific issue of the invocation ID changing can't be resolved by dbt_artifacts. I've outlined a couple of ways forward in https://github.com/brooklyn-data/dbt_artifacts/issues/53#issuecomment-997212188, would be happy to see a follow-up issue or PR for those.

**Comment by NiallRees** [comment]
@DVAlexHiggs See the linked pull request above for a proper solve!

**Comment by DVAlexHiggs** [comment]
Hi! Thanks so much. I'm gonna try this out. Any idea when it will hit release?

**Comment by NiallRees** [comment]
Using `--no-write-json` should solve the problem you were encountering today. The work going on currently should be released in the next week.
