### ISSUE TITLE
Support Databricks

### ISSUE THREAD

**Issue by amychen1776** [brooklyn-data/dbt_artifacts#61]
It would be epic to have this package support Databricks. One of the things we will need to discuss is how we will recommend loading into Databricks

**Comment by NiallRees** [comment]
Hello @amychen1776! We've been busy reimplementing the package, opening up this package to be compatible with more adapters (adding databricks compatibility out of the gate 🔥). We'd love any feedback you have: https://github.com/brooklyn-data/dbt_artifacts/releases/tag/1.0.0b1
