### ISSUE TITLE
Clarify purpose of fct_dbt__latest_full_model_executions

### ISSUE THREAD

**Issue by alanmcruickshank** [brooklyn-data/dbt_artifacts#76]
This is a question raised by #75. Incidentally, my suggestion here would be an alternate solution, which would fix the bug in that issue.

The documented intent of the `fct_dbt__latest_full_model_executions` model is:
```
A list of all models and executions times from the most recent, incremental run.
```

Our setup as a segmented approach to refreshing different marts, and so the _most recent_ run overall, will almost never contain all models. I'd like to raise the possibility of changing how this model works - or at least clarifying it's purpose. In my mind there are two options:
1. [and this is closest to the current implementation] This model has the runtimes of all the models which ran in the most recent incremental run.
2. [and this would be what I think might be more useful] This model has the runtimes of all the models in the project, based on the most recent run _in which they existed_.

The second interpretation would be much more useful in our context, but would be a change in the intent of what's going on. For any users who refresh the whole project monolithically - the main difference would be that any models which had been removed from the project would still appear in this model, just with a much older "last run" timestamp.

@NiallRees - do you think this change makes sense, or should we make a new model for this purpose?

**Comment by NiallRees** [comment]
I think 2. makes sense, though I'd suggest filtering out any models which weren't in the latest `manifest.json` rather than including all results regardless of whether the model still exists in the project.

**Comment by alanmcruickshank** [comment]
Ohh - that's a neat idea. 👍 . I like the idea of filtering on manifest. Want me to have a go at this - or is someone on your team keen?

**Comment by NiallRees** [comment]
Feel free to @alanmcruickshank! Realistically it could be a week or two before we get to it.

**Comment by alanmcruickshank** [comment]
Just having a look now - I'm going to propose that the race condition is solved by ensuring records in most of the fact and dimension tables _only_ exist if their run is present in `run_results`. That a) ensure that run results remains one of the first models executed and b) ensure that data is consistent across the package.

Are you happy with that as a solution?

**Comment by NiallRees** [comment]
That sounds perfectly reasonable @alanmcruickshank
