### ISSUE TITLE
Allow for build command artifacts to populate by adjusting filter for data:args:which = 'run'

### ISSUE THREAD

**Issue by mrevelo-clickup** [brooklyn-data/dbt_artifacts#78]
I recently implemented this package and it has been working great; however, we recently switched away from dbt run to dbt build. In doing so, I noticed that artifacts were no longer being parsed out into the fact and dimension models during a dbt_artifacts run despite being in the dbt_artifacts table.

Upon investigation, the model execution and run results models have a filter to limit the artifacts to those which are from run commands only, and not builds. I propose the filter be adjusted to `data:args:which in ('run', 'build')` for these models (or at least do the reverse and filter out non-run commands for future scalability): 

- stg_dbt__model_executions.sql
- stg_dbt__run_results
- stg_dbt__run_results_env_keys

Unless there is a reason in particular while builds are not included - please let me know. Thanks!

**Comment by NiallRees** [comment]
Hi @mrevelo-clickup, thanks for this write-up and the solution proposed. It sounds great to me :)

**Comment by mrevelo-clickup** [comment]
Only other concern is that the models may need to be re-architected around the build command since it packages together tests, snapshots, etc. Unless they are run as their own commands, I don't think they will get parsed out into their relevant test and snapshot models. Will push through the easy change to include build for now to get over the hump.

**Comment by alanmcruickshank** [comment]
@NiallRees I think this can be closed given #85 should fix the same issue.
