### ISSUE TITLE
I am not able to use Custom Schema for dbt-artifacts package

### ISSUE THREAD

**Issue by gargvipul1349** [brooklyn-data/dbt_artifacts#82]
I am not able to configure a custom schema. Can somebody please help with this?

I am getting still the **Public** schema used when I run dbt run -m dbt_artifacts.

I have set dbt_artifacts schema name and materialization but still, I am getting models been built under Public Schema.
My Configuration below in my root dbt project (dbt_project.yml)

```
# DBT_ARTIFACTS ----------------------------------------
    dbt_artifacts:
      +schema: dbt_artifacts
      +materialized: table
      incremental:
        +schema: dbt_artifacts
        +materialized: incremental
      staging:
        +schema: dbt_artifacts
        +materliazed: view
```

**Comment by ghost** [comment]
@gargvipul1349 Custom schema should be defined using the dbt_artifacts_schema var within your dbt_project.yml file and will be used in the package code when compiling the models.

example:
```
vars:
  dbt_artifacts:
    dbt_artifacts_schema: dbt_artifacts   
```

**Comment by gargvipul1349** [comment]
did same i have changed position of same and it helped.I have moved my dbt_artifacts model above models
