### ISSUE TITLE
Adding select flag information to stg_dbt__run_results

### ISSUE THREAD

**Issue by LukasSandm** [brooklyn-data/dbt_artifacts#91]
`stg_dbt__run_results` show models args as selected_models column, but since moving to dbt1, the models flag has been deprecated and the select flag is being used instead. It would be great to have the information from the select flag available in the model.

An example implementation could be replacing this line:
https://github.com/brooklyn-data/dbt_artifacts/blob/main/models/staging/stg_dbt__run_results.sql#L36

by something like the following code:
```
coalesce(data:args:models, data:args:select) as selected_models,
```
to account for projects transitioning from dbt prior to dbt1 to dbt1.

**Comment by LukasSandm** [comment]
If you see above as valid and valuable update to the package, I would also be open to contribute directly to the package and open a PR for it.

**Comment by alanmcruickshank** [comment]
I think this would be a great contribution @LukasSandm . Could you put together a PR?
